In [ ]:
import numpy as np

In [ ]:
def Cholesky(A):
    # Get the size of the matrix A
    n = len(A)

    # Initialize the lower triangular matrix L
    L = np.zeros((n, n), dtype=float)

    # Perform Cholesky decomposition
    for i in range(n):
        for k in range(i):  # Loop to calculate diagonal elements of L
            L[i, i] += L[i, k]**2
        L[i, i] = np.sqrt(A[i, i] - L[i, i])

        for j in range(i+1, n):  # Loop to calculate non-diagonal elements of L
            for k in range(i):
                L[j, i] += L[j, k] * L[i, k]
            L[j, i] = (A[j, i] - L[j, i]) / L[i, i]

    return L


In [ ]:
# Example usage:
A = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])
L = Cholesky(A)
# Display the results
print("Matrix A:")
print(A)
print("\nCholesky Decomposition:")
print("L:")
print(L)


Matrix A:
[[  4  12 -16]
 [ 12  37 -43]
 [-16 -43  98]]

Cholesky Decomposition:
L:
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]
