In [6]:
import numpy as np

In [7]:
def projection(x: np.array, y: np.array):
  return (np.dot(x, y) / np.linalg.norm(y)**2) * y

In [8]:
def gram_schmidt(x: np.array):
    # Check if there's only one vector; no orthogonalization needed
    if len(x) == 1:
        return x

    n = len(x)  # Number of rows
    m = len(x[0])  # Number of columns

    # Initialize matrices for orthogonalized vectors (e) and intermediate vectors (u)
    e = np.zeros((n, m))
    u = np.zeros((n, m))

    # Set the first vector in u and normalize to get the first vector in e
    u[:, 0] = x[:, 0]
    e[:, 0] = u[:, 0] / np.linalg.norm(u[:, 0])

    # Iterate through the remaining vectors
    for i in range(1, m):
        # Copy the original vector to u
        u[:, i] = x[:, i]

        # Subtract the projections onto previously orthogonalized vectors
        for j in range(i):
            u[:, i] -= projection(x[:, i], u[:, j])

        # Handle the case where the vector becomes a zero vector
        if np.linalg.norm(u[:, i]) > 0:
            # Normalize and store the orthogonalized vector in e
            e[:, i] = u[:, i] / np.linalg.norm(u[:, i])
        else:
            # If the vector is zero, set the corresponding vector in e to zero
            e[:, i] = 0

    return e


In [9]:
def QR(A: np.array):
    n = len(A)
    m = len(A[0])

    # Perform Gram-Schmidt orthogonalization
    e = gram_schmidt(A)

    # Initialize the upper triangular matrix R
    R = np.zeros((n, m), dtype=float)

    # Compute the entries of R
    for i in range(n):
        for j in range(i, m):
            R[i, j] = np.dot(A[:, j], e[:, i])

    return e, R


In [10]:
# Define a matrix A
A = np.array([[1, 1, 0],
              [1, 0, 1],
              [0, 1, 1]])

# Perform QR decomposition
Q, R = QR(A)
# Print the results
print("Matrix A:")
print(A)

print("\nOrthogonalized Matrix Q:")
print(Q)

print("\nUpper Triangular Matrix R:")
print(R)


Matrix A:
[[1 1 0]
 [1 0 1]
 [0 1 1]]

Orthogonalized Matrix Q:
[[ 0.70710678  0.40824829 -0.57735027]
 [ 0.70710678 -0.40824829  0.57735027]
 [ 0.          0.81649658  0.57735027]]

Upper Triangular Matrix R:
[[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]
