In [1]:
import numpy as np

In [12]:
def inverse(matrix: np.array):
    # Get the size of the matrix
    n = len(matrix)

    # Create an identity matrix of the same size
    I = np.eye(n)

    # Perform Gaussian elimination with partial pivoting
    for i in range(0,n-1):
        # Check for singularity
        if matrix[i, i] == 0:
            raise ValueError("Matrix is singular and cannot be inverted.")

        for j in range(i+1, n):
            # Calculate the factor for row reduction
            factor = matrix[j, i] / matrix[i, i]

            # Update both the identity matrix and the input matrix
            I[j,i:] -= (factor * I[i, i:])
            matrix[j, i:] -= (factor * matrix[i, i:])
            # print(matrix)

    # Check for singularity
    if matrix[n-1, n-1] == 0:
        raise ValueError("Matrix is singular and cannot be inverted.")

    # Perform back substitution
    for i in range(n-1, 0, -1):
        for j in range(i-1, -1, -1):
            # Calculate the factor for back substitution
            factor = matrix[j, i] / matrix[i, i]

            # Update both the identity matrix and the input matrix
            I[j, :] -= factor * I[i, :]
            matrix[j, :] -= factor * matrix[i, :]

    # Normalize the diagonal elements to 1
    for i in range(n):
        if matrix[i, i] != 1:
            factor = matrix[i, i]
            matrix[i, :] /= factor
            I[i, :] /= factor

    # Return the inverse matrix
    return I

# Example usage:
# Uncomment and replace the following lines with your own matrix
A = np.array([[2.0, -1.0, 0.0], [-1.0, 2.0, -1.0], [0.0, -1.0, 2.0]], dtype=float)
#print("Result using numpy:\n", np.linalg.inv(A))
result = inverse(A)
print("Original Matrix:\n", A)
print("Inverse Matrix:\n", result)

Result using numpy:
 [[0.75 0.5  0.25]
 [0.5  1.   0.5 ]
 [0.25 0.5  0.75]]
Original Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Inverse Matrix:
 [[0.66666667 0.5        0.25      ]
 [0.33333333 1.         0.5       ]
 [0.         0.5        0.75      ]]
