In [1]:
import numpy as np

In [10]:
def projection(x: np.array, y: np.array):
    """
    Calculate the projection of vector x onto vector y.

    Parameters:
    - x (numpy array): The vector to be projected.
    - y (numpy array): The vector onto which x is projected.

    Returns:
    numpy array: The projection of vector x onto vector y.

    Explanation:
    The projection of vector x onto vector y is calculated using the formula:
    proj_y(x) = (dot(x, y) / ||y||^2) * y
    where dot(x, y) is the dot product of x and y, ||y|| is the norm of y.

    The formula involves scaling the vector y by the scalar (dot(x, y) / ||y||^2),
    resulting in the vector projection of x onto the direction of y.
    """
    return (np.dot(x, y) / np.linalg.norm(y)**2) * y


In [13]:
def gram_schmidt(x: np.array):
    """
    Apply the Gram-Schmidt process to orthogonalize a set of vectors.

    Parameters:
    - x (numpy array): Matrix where each column represents a vector to be orthogonalized.

    Returns:
    numpy array: Matrix containing orthogonalized vectors.

    Description:
    The Gram-Schmidt process is used to orthogonalize a set of vectors. The function takes
    a matrix x where each column represents a vector, and it returns a matrix of
    orthogonalized vectors.

    The process involves initializing two matrices: e for orthogonalized vectors and u for
    intermediate vectors. The first vector in u is set to the first vector in x, and the
    corresponding vector in e is normalized.

    Then, for each subsequent vector in x, the function subtracts its projections onto
    previously orthogonalized vectors in u. If a vector becomes a zero vector during this
    process, the corresponding vector in e is set to zero.

    The resulting matrix e contains the orthogonalized vectors.
    """
    # Check if there's only one vector; no orthogonalization needed
    if len(x) == 1:
        return x

    n = len(x)  # Number of rows
    m = len(x[0])  # Number of columns

    # Initialize matrices for orthogonalized vectors (e) and intermediate vectors (u)
    e = np.zeros((n, m))
    u = np.zeros((n, m))

    # Set the first vector in u and normalize to get the first vector in e
    u[:, 0] = x[:, 0]
    e[:, 0] = u[:, 0] / np.linalg.norm(u[:, 0])

    # Iterate through the remaining vectors
    for i in range(1, m):
        # Copy the original vector to u
        u[:, i] = x[:, i]

        # Subtract the projections onto previously orthogonalized vectors
        for j in range(i):
            u[:, i] -= projection(x[:, i], u[:, j])

        # Handle the case where the vector becomes a zero vector
        if np.linalg.norm(u[:, i]) > 0:
            # Normalize and store the orthogonalized vector in e
            e[:, i] = u[:, i] / np.linalg.norm(u[:, i])
        else:
            # If the vector is zero, set the corresponding vector in e to zero
            e[:, i] = 0

    return e


In [14]:
# Example set of vectors (columns of the matrix)
v1 = np.array([1, 1, 0])
v2 = np.array([1, 0, 1])
v3 = np.array([0, 1, 1])

# Create a matrix with these vectors as columns
matrix_x = np.column_stack((v1, v2, v3))

# Apply the Gram-Schmidt process
orthogonalized_matrix = gram_schmidt(matrix_x)

# Display the original and orthogonalized matrices
print("Original Matrix:")
print(matrix_x)

print("\nOrthogonalized Matrix:")
print(orthogonalized_matrix)


Original Matrix:
[[1 1 0]
 [1 0 1]
 [0 1 1]]

Orthogonalized Matrix:
[[ 0.70710678  0.40824829 -0.57735027]
 [ 0.70710678 -0.40824829  0.57735027]
 [ 0.          0.81649658  0.57735027]]
