In [12]:
#import necessary library
import numpy as np
import time
from scipy.linalg import lu

In [13]:
#create matrix
matrix=np.random.randint(-1,11,size=(20,20))

In [14]:
#showing the matrix
print(matrix)

[[ 7  9  4 10  5  1  3  3  3  4  4  3  3  9  2  1  6  9 10  3]
 [ 1  5 -1  6  8  8  3  7  2 10  4  8 10  2  9  1 10  7  9  7]
 [ 6  1  4  0  4  7  4 -1 10  6  5  5 10  7  4  3  4 10  7  0]
 [ 6  7  4  6  8  4  1 10  8  3 -1  9  3  6  9  7  5  6  8  8]
 [-1 -1 10  5  0 10  4 -1  3  1 -1  9 10 10  6  2  9  6  2  8]
 [ 7 10  4  3  9 -1  3 -1  6  8  2  3  9  1 10  9  4  8  1  4]
 [ 7 10 -1  8 -1 -1  5 10  9  1  8 10  2  5 10 -1  8  0  7  2]
 [10  6  5  2  4  2  9  6 -1  6  9 10  1  4  8  7  6  3  1 -1]
 [ 6  4  1  5  5 -1 10  5  1  3  7  1  3 10  7  9  8  3  3  9]
 [-1  7  2  1  5  3  5  0  2  3  7  8  1  2  9  9  2  1  7  0]
 [ 9  6  5  6  4 10  8  7  8  4  6 10  6  3  5  1 -1 10  4 10]
 [10  9  6  8  2  8  5  0  1  9  1  6 10 -1  0 10 10  2  4  1]
 [-1  2  5  2  9  8  3  6  9 10  7  8  9  9  5 10  8  6  2 -1]
 [ 0 -1 -1  8 10 10  0  3  5  9  5  9  2  4  2 -1  3 10  1  3]
 [ 0  6  0  5  6 10  5  1  0  0  0  3  5  1  2  6  8  4  2  7]
 [ 2  3  4 -1  0 -1  9  0  8 10  5  3  2  3 10  6  4  0

In [15]:
import numpy as np
import time

# Start measuring the execution time
start_time = time.time()

def lu(matrix: np.array):
    # taking the length of the row (square matrix)
    n = len(matrix)
    # taking the length of the column
    n1 = len(matrix[0])
    if n != n1:
        return -1  # Return -1 if the matrix is not square

    # initializing P, L, U matrices
    P = np.eye(n)  # P is an identity matrix to start with
    L = np.eye(n)  # L is initialized as an identity matrix
    U = matrix.copy()  # U is a copy of the original matrix

    for i in range(n-1):
        # finding the largest element column-wise
        pivot_index = np.argmax(np.abs(U[i:, i])) + i  # i is added to correct the index of the matrix

        # partial pivoting (switch the initial row with the pivot row to arrange the increasing order of the pivot element)
        U[[i, pivot_index], :] = U[[pivot_index, i], :]
        L[[i, pivot_index], :] = L[[pivot_index, i], :]
        P[[i, pivot_index], :] = P[[pivot_index, i], :]

        # Gauss elimination
        for j in range(i+1, n):
            factor = U[j, i] / U[i, i]
            L[j, i] = factor  # Store the multiplier in the L matrix
            U[j, i:] = U[j, i:] - (factor * U[i, i:])  # Apply the row operation

    return P, L, U

# Example usage:
P, L, U = lu(matrix)
print("Permutation matrix (P):")
print(P)
print("\nLower triangular matrix (L):")
print(L)
print("\nUpper triangular matrix (U):")
print(U)

# End measuring the execution time
end_time = time.time()
print("Execution time:", end_time - start_time)


Permutation matrix (P):
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [16]:
# Assuming matrix is defined before this code
start_time = time.time()

# Call the LU decomposition function
p, l, u = lu(matrix)

# Print the results
print("Permutation matrix (P):")
print(p)
print("\nLower triangular matrix (L):")
print(l)
print("\nUpper triangular matrix (U):")
print(u)

# Measure and print the execution time
end_time = time.time()
print("Execution time:", end_time - start_time)


Permutation matrix (P):
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.